### ISSUE TITLE
Multi module project with different git repositories

### ISSUE THREAD

**Issue by mbrasil** [jgitver/jgitver-maven-plugin#103]
**version**: 1.4.2

**usage context**:

- [x] maven command line: 3.5.2
- [x] git: 2.19.1.windows.1

**Problem description**:

I would like to know if it would be possible to use this plugin for a project with the following configuration:

Parent project
      | - Sub parent project
                | - WAR project
                | - EAR project
      | - Sub parent 2 project
                | - WAR project
                | - EAR project

Since the "Sub parent" project would be something like the "multi-module" example. If I do at the level of "Sub parent", the plugin works without problems. But if you do at the "Parent project" level, I can not fetch their versions correctly. Each of the "Sub Parent" projects has its own git repository and its respective version. The "EAR project" uses the "WAR project" and the "Parent project" is just an agregator.

Is it possible to do something like this?

**Comment by McFoggy** [comment]
sorry in current state of the jgitver there could be only one-root ; in your case it should be the "Parent project"

- Why do you group both sub projects together if they have their own lifecycle.
- Isn't such a setup only for a developer perspective to ease the developer life? If yes then I would just suggest to deactivate jgitver for the import mechanism in your prefered IDE.

**Comment by mbrasil** [comment]
Many thanks for the quick response. It left me thinking about the model we are currently using and I'll try to think of a better way to organize the projects. Thank you!

One last question, if you please, using the multi-module example and imagining that the api project has a dependency on another project that is maintained by us, like a shared library, and this project has another git repository. For your answer, I believe it is not currently possible to fetch the version of this library using the jgitver plugin. Right?

Thank you very much for your time and congratulations for the excellent plugin.

**Comment by McFoggy** [comment]
for dependencies management I would say that the problem is not that much jgitver related ; but it can be amplified by jgitver usage and dynamic versioning.

Suppose that today for each commit you do a `mvn release` to have a unique versions for each commit/feature. 
How would you handle your dependency in a consumer project?

When you answer this you have to consider 2 different use cases:
- the developer use case within it's IDE
- the maven build itself

What I do in my projects:

- I fix all projects version to `0` in the pom.xml
- in the dependency section I try to always use a reference to a property
```
<properties>
    <lib.version>2.0.0</lib.version>
</properties>
...
<dependency>
    <groupId>com.mycompany</groupId>
    <artifactId>lib</artifactId>
    <version>${lib.version}</version>
</dependency>
```
this property can contain a fixed version, a SNAPSHOT one, a range.
- for IDE imports, I use a specific profile
```
<profiles>
    <profile>
        <id>IDE</id>
        <properties>
            <lib.version>0</lib.version>
        </properties>
    </profile>
</profiles>
```
that way when I import the `app` project referencing the `lib` project it resolve it with a version 0 which , if you have followed the first bullet, is the version in the lib's pom.xml which will be used by the IDE (eclipse, netbeans, and Intellij when you deactivate jgitver during project import)
- before releases, I ensure using the [maven dependency plugin](https://maven.apache.org/plugins/maven-dependency-plugin/) that the lib version gets fixed in the property

I need to put all that in the documentation.
Hope it helps you already.

**Comment by mbrasil** [comment]
Thanks again for the quick response. Your response has helped a lot to think about what to do to solve my problem. I was thinking of using jgitver throughout my project and use it like you suggested. Then update the property using the plugin [versions](https://www.mojohaus.org/versions-maven-plugin/index.html) with the goal "versions: update-property "to update after deploying my lib.
Again thanks for the help.

**Comment by McFoggy** [comment]
I think you got it right.
