### ISSUE TITLE
Plugin doesn't work with forking plugins

### ISSUE THREAD

**Issue by genuss** [jgitver/jgitver-maven-plugin#109]
## Issue

**version**: 1.4.4

**usage context**:

- [ ] maven command line: mvn clean install

**Problem description**:

I found some issues when building war-project which is deployed during deploy phase. To make things easier to reproduce, I created minimal example here: https://github.com/genuss/jgitver-test-project

To reproduce just do
````bash
git clone https://github.com/genuss/jgitver-test-project.git
cd jgitver-test-project
mvn clean install
````

You will get the following output: [mvn.log](https://github.com/jgitver/jgitver-maven-plugin/files/2699915/mvn.log)

The interesting part is that maven performs lifecycle phases the second time after trying to fork for deploying to tomcat. This moment can be found by searching for `>>>`.

**Workaround**:

Changing goal from `deploy` to `deploy-only` helps to get it work.

**Comment by McFoggy** [comment]
OK got it to work with a still undocumented feature, the usage of [maven-flatten-plugin](https://www.mojohaus.org/flatten-maven-plugin/),

## quick solution

with 1.4.4 you can launch your build with `-Djgitver.flatten=true` 

_see below for a hint to persist/share this setting_

```
mvn clean install -Djgitver.flatten=true
...
[INFO] --- maven-war-plugin:2.4:war (default-war) @ test-project ---
[INFO] Packaging webapp
[INFO] Assembling webapp [test-project] in [D:\dev\projects\personnal\oss\jgitver\samples\issues\maven-issue-109\jgitver-test-project\target\test-project-0.0.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp webResources [D:\dev\projects\personnal\oss\jgitver\samples\issues\maven-issue-109\jgitver-test-project\web] to [D:\dev\projects\personnal\oss\jgitver\samples\issues\maven-issue-109\jgitver-test-project\target\test-project-0.0.0-SNAPSHOT]
[INFO] Webapp assembled in [58 msecs]
[INFO] Building war: D:\dev\projects\personnal\oss\jgitver\samples\issues\maven-issue-109\jgitver-test-project\target\test-project-0.0.0-SNAPSHOT.war
[INFO]
[INFO] <<< tomcat7-maven-plugin:2.2:deploy (default) < package @ test-project <<<
[INFO]
[INFO]
[INFO] --- tomcat7-maven-plugin:2.2:deploy (default) @ test-project ---
[INFO] Déployment du war sur http://localhost:8080/test-project
Uploading: http://localhost:8080/manager/text/deploy?path=%2Ftest-project
Uploaded: http://localhost:8080/manager/text/deploy?path=%2Ftest-project (4 KB at 397.8 KB/sec)
```

## issue description

The issue comes from the basedir location during the fork execution. When the fork occurs, the basedir is not retained from the initial project but is computed from the pom.xml location at the time the fork occurs. With current jgitver, the pom.xml is copied in TEMP directory, modified to reflect changes & referenced inside the POM (as object model in memory). 
On my machine, when the fork occurs, the basedir is computed as 
```
...
[DEBUG]   (f) basedir = D:\Users\awxgx\AppData\Local\Temp
...
[DEBUG]   (s) project = MavenProject: test:test-project:0.0.0-SNAPSHOT @ D:\Users\awxgx\AppData\Local\Temp\pom2049150230066578848.jgitver-maven-plugin.xml
```

The basedir in this situation is wrong and should remain as the original one ; ie the location of the initial pom.

I will have to discuss the topic with maven committers to see if the basedir cannot be retained when the fork is issued.

Hopefully, very recently in e851ee7c3e081ab186349cee41fe5c027b86a6c9, which is part of `1.4.4` I added as an optional feature the possibility to use maven-flatten-plugin instead of the pom update feature inside jgitver-maven-plugin. If you switch to it, instead of having a modified file inside the TEMP dir you'll get a modified file just beside your initial pom.xml. The effect will be that the basedir will be the same than the original one and thus that your build will work.
So for the moment just activate maven-flatten-plugin by setting the `-Djgitver.flatten=true` property.

In order to share the setting with your teammates or your CI, you can do it inside a `.mvn\jvm.config` file and commit the file.

```
myproject$ cat .mvn\jvm.config
-Djgitver.flatten=true
myproject$
```

look at e851ee7c3e081ab186349cee41fe5c027b86a6c9 commit message to have more capabilities on the new feature.

**Comment by genuss** [comment]
Yes, with flatten-plugin it all works however resulting pom will be very different from what is in source code. One should keep this in mind.
Looks like the problem with base directory is more maven issue than a jgitver.

Thank you for workaround. To summarize we have to workarounds:
1. We can use flatten-plugin
2. We can replace forking executions with non-forking where applicable.

**Comment by McFoggy** [comment]
> Yes, with flatten-plugin it all works however resulting pom will be very different from what is in source code. One should keep this in mind.

yes but deployed file should not be used to retain build information. It make sense to start changing our mind on that. 

> To summarize we have 2 workarounds:
> 
> 1. We can use flatten-plugin
> 1. We can replace forking executions with non-forking where applicable.

you got it.

> Thank you for workaround.

you're welcome.

**Comment by genuss** [comment]
> yes but deployed file should not be used to retain build information. It make sense to start changing our mind on that.

Indeed. But not many yet understand that.

**Comment by McFoggy** [comment]
I'll help soon in doing the opposite: flatten by default and optionally retain old behavior ;-)
