### ISSUE TITLE
jgitver issues with nexus-staging-maven-plugin

### ISSUE THREAD

**Issue by chizou** [jgitver/jgitver-maven-plugin#114]
I'm having an issue using the nexus-staging-maven-plugin in conjunction with jgitver. When trying to deploy the example application, I get the following error:
```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6:deploy 
(default-deploy) on project jgitver-tester: Failed to deploy artifacts: Could not transfer 
artifact com.company:jgitver-tester:jar:1.0.1 from/to nexus 
(https://nexus.example.com/repository/fmgeo-snapshots/): Failed to transfer file: 
https://nexus.example.com/repository/fmgeo-snapshots/com/company/jgitver-tester/1.0.1/jgitver-tester-1.0.1.jar.
Return code is: 400, ReasonPhrase: Repository version policy: SNAPSHOT does not allow version:
1.0.1. -> [Help 1]
```

Steps for reproduction are below:
```
# the pom just contains the settings for our nexus repo
cp /tmp/pom.xml .
git tag 1.0.1 -m "Release 1.0.1"
mvn -P jenkins deploy -DskipStaging=true
git checkout cool-feature
git merge master -Xtheirs master -m "merge"
echo "Hello world" > content
git add content pom.xml
git commit -m "Hello world"
git checkout master
git merge cool-feature
mvn -P jenkins deploy -DskipStaging=true
```

So I thought maybe I had an issue that required me to set a tag to push to release. So I try the following...
```
git tag 1.0.2 -m "release 1.0.2"
mvn -P jenkins deploy -DskipStaging=true
```
Doing that gives me the following error...
```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6:deploy
(default-deploy) on project jgitver-tester: Failed to retrieve remote metadata
com.company:jgitver-tester:1.0.2-cool_feature-SNAPSHOT/maven-metadata.xml: Could
not transfer metadata com.company:jgitver-tester:1.0.2-cool_feature-SNAPSHOT/maven-metadata.xml 
from/to nexus (https://nexus.example.com/repository/fmgeo-releases/): Failed to transfer file: 
https://nexus.example.com/repository/fmgeo-releases/com/company/jgitver-tester/1.0.2-cool_feature-SNAPSHOT/maven-metadata.xml.
Return code is: 400 , ReasonPhrase:Repository version policy: RELEASE does not allow metadata in
path: com/company/jgitver-tester/1.0.2-cool_feature-SNAPSHOT/maven-metadata.xml. -> [Help 1]

```

Seems like if I try to deploy to snapshots, it tries to deploy a release. If I try to deploy to release, it tries to deploy a snapshot. Any insight on how we can fix this?

**Comment by McFoggy** [comment]
jgitver itself uses [nexus-staging-maven-plugin](https://github.com/jgitver/jgitver-maven-plugin/blob/master/pom.xml#L701) in order to deploy to sonatype and then to maven central.
Most of the time I deploy only release version of jgitver (and plugins) but I did it already for some SNAPSHOT versions as well ; so I am 100% sure it works for both cases.

![carbon 1](https://user-images.githubusercontent.com/1119660/52768676-6c976200-302e-11e9-9717-d98d9d16a34f.png)

From the commands you are executing:
- I suppose that you have a _default_ jgitver maven configuration (sorry I do not know it)
- line 3 : here the version computed by jgitver should be a release one
- line 11 : here the version computed should be a SNAPSHOT one because you are far away from the tag and using a default jgitver maven policy.

I'd like to help but honestly I lack a lot of information:
- jgitver-maven-plugin version
- nexus-staging-maven-plugin version
- configuration (pom & jgitver config)

For the failing
```
git tag 1.0.2 -m "release 1.0.2"
mvn -P jenkins deploy -DskipStaging=true
```
just after the tag, can you execute the following commands and provide outputs:
- `git log --no-color --graph --pretty=format:"%h -%d" --abbrev-commit -n 5`
- `mvn validate`

Ideally, if you can, expose a repoducer case.
If you have nexus involved, perhaps a docker-compose setup could be provided to reproduce the problem.

**Comment by McFoggy** [comment]
@chizou I have pushed some samples to demo nexus integration:
- nexus standard deployment: https://github.com/jgitver/jgitver-samples/tree/master/nexus-deployment/nexus-oss
- nexus deployment with staging: https://github.com/jgitver/jgitver-samples/tree/master/nexus-deployment/nexus-pro-with-staging

Unfortunatelly I cannot provide a fully functionnal sample for nexus PRO as it requires a license.
But if you can try to reproduce using the provided nexus PRO sample application.

**Comment by chizou** [comment]
@McFoggy thanks for providing all of that. I've forked your example and created a branch that recreates the issue, sort of. I can't get it to output errors the same way I was getting output above, but you can see the issues in the activity log. I made a few changes to the `docker-compose.yaml` file to resemble my use case a bit closer (Java8 and Nexus3).

My forked branch is here: https://github.com/chizou/jgitver-samples/tree/example-issue-114/nexus-deployment/nexus-oss/bad-project and the `README.md` should explain the issue I'm seeing.

After doing all of this, I'm not certain if my issue is with jgitver or `nexus-staging-maven-plugin`. 

If you could please tell me what I'm doing wrong, I'd greatly appreciate that. Thanks!

**Comment by McFoggy** [comment]
@chizou are you sure that _nexus-staging-maven-plugin_ can be used against an OSS version of nexus?

The documentation regarding staging is only for the PRO version :https://help.sonatype.com/repomanager3/repository-manager-pro-features.

If staging feature cannot be use, why not using the standard maven deployment?

**Comment by McFoggy** [comment]
taken from https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin
![image](https://user-images.githubusercontent.com/1119660/52839338-10981080-30f6-11e9-8838-485f8674d058.png)

**Comment by McFoggy** [comment]
not an issue with jgitver
