### ISSUE TITLE
Annotated and lightweight tag on same commit result in -SNAPSHOT version

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#12]
I have created a lightweight "v74" and "74" tag on the same commit.
Unfortunately this seem to result in a "74.0.0-SNAPSHOT" version.

Deleting the light weight tag results in the version number 74.0.0

**Comment by McFoggy** [comment]
looks like a bug. It works as expected when on a detached head.

**Comment by McFoggy** [comment]
In fact looks like it is currently an expected behavior... at least it is exactly tested to be that result in jitver unit test [Scenario12WithDefaultsTest](https://github.com/jgitver/jgitver/blob/0.1.0/src/test/java/fr/brouillard/oss/jgitver/strategy/maven/defaults/Scenario12WithDefaultsTest.java#L166).

I need to think a bit more about it ; quickly I would be in favor of returning the annotated tag. It is the behavior on a detached head (for example when you checkout a past tag). Being on HEAD in a branch is treated in a particular way in jgitver and the above test shows that it was really developped and thought initially to send the result you have noticed.

I'll come back to this defect ; I need the night to think about it ;-)

**Comment by jschneider** [comment]
The scenario happened as follows:

I am on develop after a release.
- Making one change
- Updating to new major version

Now I want to release the version
- checkout master
- merge develop
- create final version tag
- mvn clean deploy -DperformRelease

I think this might be a common workflow (very git flow-ish).

**Comment by McFoggy** [comment]
@jschneider I finally retrieved why it is currently like that.

I agree your scenario could sense and to make it fully functionnal just add one line: `git checkout TAGNAME`. You'll then be not anymore on the branch HEAD but on a detached HEAD and it will work.

The current behavior has to be explained only by one thing: a lack of support of dirty repository.
Because while developping what's also make sense is the following:
- you're on HEAD/master that is tagged for release `1.0.0`
- you want to start developping 2.0, thus: git tag `v2.0.0`
- make one change locally without commiting, `mvn validate` => you expect V2.0.0-SNAPSHOT not 1.0.0.

So as a workaround for the moment introduce in your process a single line `git checkout RELEASE_TAG` before `mvn clean deploy -DperformRelease`

**Comment by McFoggy** [comment]
here is a reproducer for your scenario, first `mvn validate` demonstrates the usage of the light tag, the second `mvn validate` on detached head of the released tag demonstrates the usage of the annotated tag

```
cd /d
rm -rf /d/demo-jgitver-maven-plugin
mkdir -p /d/demo-jgitver-maven-plugin
cd /d/demo-jgitver-maven-plugin
git init
git config user.name someone
git config user.email someone@nowhere.com
cat > pom.xml << EOF
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.brouillard.oss.demo</groupId>
    <artifactId>demo-jgitver-maven-plugin</artifactId>
    <version>0</version>
    <packaging>pom</packaging>
    <build>
        <extensions>
            <extension>
                <groupId>fr.brouillard.oss</groupId>
                <artifactId>jgitver-maven-plugin</artifactId>
                <version>[0.1.1,)</version>
            </extension>
        </extensions>
    </build>
</project>
EOF
echo A > content
git add pom.xml
git add content
git commit -m "initial commit"
echo B > content && git add -u && git commit -m "added B data"
git tag 1.0 -m "release 1.0"
git tag v2.0
mvn validate
git checkout 1.0
mvn validate
```

**Comment by McFoggy** [comment]
@jschneider jgitver/jgitver#9 should answer your need.

**Comment by McFoggy** [comment]
with version `0.2.0-alpha1` you now have the correct behavior.

A dirty check is now done to use either light or annotated tags when on HEAD in a branch.

using the following

```
cd /d
rm -rf /d/demo-jgitver-maven-plugin
mkdir -p /d/demo-jgitver-maven-plugin
cd /d/demo-jgitver-maven-plugin
git init
git config user.name someone
git config user.email someone@nowhere.com
cat > pom.xml << EOF
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.brouillard.oss.demo</groupId>
    <artifactId>demo-jgitver-maven-plugin</artifactId>
    <version>0</version>
    <packaging>pom</packaging>
    <build>
        <extensions>
            <extension>
                <groupId>fr.brouillard.oss</groupId>
                <artifactId>jgitver-maven-plugin</artifactId>
                <version>[0.2.0-alpha1,)</version>
            </extension>
        </extensions>
    </build>
</project>
EOF
echo A > content
git add pom.xml
git add content
git commit -m "initial commit"
echo B > content && git add -u && git commit -m "added B data"
git tag 1.0 -m "release 1.0"
git tag v2.0
mvn validate
touch newFile
mvn validate
```

first validate returns correctly 1.0.0
and second one (with the repository dirty) 2.0.0-SNAPSHOT

**Comment by jschneider** [comment]
Does not work for me.
I get that output:

```
Initialized empty Git repository in /tmp/c/d/demo-jgitver-maven-plugin/.git/
[master (root-commit) 107b478] initial commit
 2 files changed, 17 insertions(+)
 create mode 100644 content
 create mode 100644 pom.xml
[master 70a9555] added B data
 1 file changed, 1 insertion(+), 1 deletion(-)
[INFO] Scanning for projects...
[INFO] jgitver-maven-plugin is about to change project(s) version(s)
[INFO]     fr.brouillard.oss.demo::demo-jgitver-maven-plugin::0 -> 2.0.0-SNAPSHOT
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building demo-jgitver-maven-plugin 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.408 s
[INFO] Finished at: 2016-07-02T10:24:59+02:00
[INFO] Final Memory: 11M/303M
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] jgitver-maven-plugin is about to change project(s) version(s)
[INFO]     fr.brouillard.oss.demo::demo-jgitver-maven-plugin::0 -> 2.0.0-SNAPSHOT
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building demo-jgitver-maven-plugin 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.333 s
[INFO] Finished at: 2016-07-02T10:25:00+02:00
[INFO] Final Memory: 11M/303M
[INFO] ------------------------------------------------------------------------
```

**Comment by jschneider** [comment]
I create a new issue with another idea. Maybe that could solve that.

**Comment by McFoggy** [comment]
reopen, looking at jgitver-maven-plugin-0.2.0-alpha1 jar metadata revealed a wrong version ; I'll deploy an alpha2 to correct that

**Comment by McFoggy** [comment]
@jschneider I have rechecked with a clean maven local repository, and indeed with previous ranges in use and my local modifications I had some wrong results using alpha1.  
Now with alpha2, I use fixed version so that everything has to be really reproducable. Please reopen if the following does not execute correctly for you.

```
cd /d
rm -rf /d/demo-jgitver-maven-plugin
mkdir -p /d/demo-jgitver-maven-plugin
cd /d/demo-jgitver-maven-plugin
git init
git config user.name someone
git config user.email someone@nowhere.com
cat > pom.xml << EOF
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.brouillard.oss.demo</groupId>
    <artifactId>demo-jgitver-maven-plugin</artifactId>
    <version>0</version>
    <packaging>pom</packaging>
    <build>
        <extensions>
            <extension>
                <groupId>fr.brouillard.oss</groupId>
                <artifactId>jgitver-maven-plugin</artifactId>
                <version>0.2.0-alpha2</version>
            </extension>
        </extensions>
    </build>
</project>
EOF
echo A > content
git add pom.xml
git add content
git commit -m "initial commit"
echo B > content && git add -u && git commit -m "added B data"
git tag 1.0 -m "release 1.0"
git tag v2.0
mvn validate
touch newFile
mvn validate
```

First `mvn validate` should resolve 1.0.0 and second one, with dirty state, should resolve 2.0.0-SNAPSHOT
