### ISSUE TITLE
Code detected as "dirty" when nothing is modified

### ISSUE THREAD

**Issue by archiecobbs** [jgitver/jgitver-maven-plugin#125]
## Issue

I like and use the `<useDirty>` feature. However, it's behavior is a little too aggressive.

What I would expect is that the code is considered "dirty" if and only if `git describe --dirty=XXX` would append the `XXX`.

However, jgitver and `git describe` disagree in the situation where the code is clean, but an unknown file exists.

Example:

```
$ git status
On branch maven
Your branch is up to date with 'repo/maven'.

nothing to commit, working tree clean
$ git describe --dirty=XXX
1.2.0-20-g1d3a0d77
$ touch foo
$ git status
On branch maven
Your branch is up to date with 'repo/maven'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	foo

nothing added to commit but untracked files present (use "git add" to track)
$ git describe --dirty=XXX
1.2.0-20-g1d3a0d77
$ mvn clean
[INFO] Using jgitver configuration file: /home/archie/pcom/.mvn/jgitver.config.xml
[INFO] Using jgitver-maven-plugin [1.5.1] (sha1: e45d1669b39cedb98720dd33cc14d0185b455ca1)
[INFO]     version '1.2.0-20-1d3a0d77-dirty' computed in 1197 ms
```

The version string calculated by jgitver in this example should be `1.2.0-20-1d3a0d77`, not `1.2.0-20-1d3a0d77-dirty`.

**Comment by McFoggy** [comment]
Sorry but I think in this case jgitver is `true` in the way that having a new file in your project may change the output/content of your build or way your runtime might perform ; so it is a way to warn you that something can go wrong.  
Indeed with such a feature activated you have to really take care of your .gitignore file so that unexpected files (IDE ones especially, or build results ones) do not interfere with the computed version and the dirty status.

On the other hand you can open a feature request in [jgitver](https://github.com/jgitver/jgitver/issues) describing your need.  
Please when filling it try to consider all possibilities:
- new vs modified files
- files in workdir vs index
- ...

and ways to handle the configuration: which configuration items to add /modify with what kind of value

**Comment by archiecobbs** [comment]
Filed as https://github.com/jgitver/jgitver/issues/100
