### ISSUE TITLE
replace project.version with value

### ISSUE THREAD

**Issue by soloturn** [jgitver/jgitver-maven-plugin#129]
maven knows ${project.version} and ${parent.project.version}. e.g for a project which has modules a and b, b depends on a one can use project.version. unfortunately on "mvn install" or "mvn deploy" the fields stay as is, $project.version.

if one wants to inherit something, $project.version is in there, not the parent projects version is displayed, but the version of the component. this may fail as it searches now the parent with the version of the child.

it would be nice if jgitver could replace the ${project.version} before install/depoy so no uncertainty is left which version to take.

**Comment by McFoggy** [comment]
@soloturn can you explain a bit more your issue ?

> unfortunately on "mvn install" or "mvn deploy" the fields stay as is, $project.version

this is not what is expected. When doing `mvn clean install` on the **multi-module** sample example (https://github.com/jgitver/jgitver-samples/tree/master/multi-module) the installed POM in the maven local repository are correct with the computed version by jgitver.

Do you see a different behavior?

**Comment by merikan** [comment]
I have the same problem  in my projects. As you say, it works when running install and deploy phases but not when running deploy:deploy goal.

I have a multi-step build pipeline with the following main steps:
1. Build: ` mvn clean package -DskipTests`
1. Test:  ` mvn test`
1.  Publish: `mvn validate jar:jar source:jar-no-fork  deploy:deploy`

When running the last step every sub-module points to parent with version 0

**Comment by McFoggy** [comment]
@merikan indeed by calling individual tasks I think you bypass totally the [default lifecycle](http://maven.apache.org/ref/3.6.3/maven-core/lifecycles.html#default_Lifecycle) to which jgitver adds some task execution.

Why do you call those individual tasks and not `mvn deploy` ?

**Comment by merikan** [comment]
Hi @McFoggy 
the reason is that in my pipeline the first step builds all artifacts, jars (bin and source), docker images etc and I don't want maven to rebuild those artifacts in a later step.
When running the `deploy` phase maven will execute each default lifecycle phase (validate, compile, package, etc.) before running deploy.

**Comment by McFoggy** [comment]
@merikan I understand that you want to bypass or execute things in a finer way. But in maven, the _normal way_ (AFAIK) to do this is not to bypass lifecycles it is by using profiles.

**Comment by merikan** [comment]
@McFoggy You may be right that profiles are the way to go, but I think I have tried all combinations without success. What would it look like to achieve the same behavior with the help of profiles?

Anyway, my setup partly works with jgitver because the artifacts ends up in the right directory, with the right version, and all the projects get the right version in the pom but the children points to parent:0. So jgitver is executed but for some reason the maven deploy plugin doesn't recognize the parent version.
I tried to debug the maven deploy plugin and I can see that it uses the by jgitver calculated parent version but for some reason it's not what get transferred to the repository. I had some trouble debugging  the code since I have a missmatch between the byte code and the source code in the maven-artifact-transfer jar (0.10.0)

**Comment by McFoggy** [comment]
@merikan I found a workaround.
As I told you jgitver needs at some point to add the execution of a goal inside the build lifecycle (see [source code](https://github.com/jgitver/jgitver-maven-plugin/blob/master/src/main/java/fr/brouillard/oss/jgitver/JGitverModelProcessor.java#L290)). By default the execution of this goal is tied to `prepare-package` phase ; which is not executed in your case.
Fortunately, there is a waiting for use hook in the [code](https://github.com/jgitver/jgitver-maven-plugin/blob/master/src/main/java/fr/brouillard/oss/jgitver/JGitverModelProcessor.java#L325) : we can tell jgitver to execute this goal during another phase by setting the property `jgitver.pom-replacement-phase`.
In you case calling `mvn validate jar:jar source:jar-no-fork deploy:deploy -Djgitver.pom-replacement-phase=validate` should do the trick.

I verified it on the [multi-module sample](https://github.com/jgitver/jgitver-samples/tree/master/multi-module) project using the following: `mvn validate jar:jar install:install -Djgitver.pom-replacement-phase=validate`

There is also another feature, in which you can disable this jgitver replacement goal by the usage of [flatten-maven-plugin](https://www.mojohaus.org/flatten-maven-plugin/). 
Find some instructions in the [CHANGELOG](https://github.com/jgitver/jgitver-maven-plugin/blob/master/CHANGELOG.md#github-102-study-usage-of-maven-flatten-plugin) to try it or look into [the code](https://github.com/jgitver/jgitver-maven-plugin/blob/master/src/main/java/fr/brouillard/oss/jgitver/JGitverModelProcessor.java#L152-L161) the usage of flatten.

**Comment by merikan** [comment]
@McFoggy this is awesome. I added `-Djgitver.pom-replacement-phase=validate` and now 
 everything looks perfect. This was what I needed. Thanks a lot. 👍

**Comment by McFoggy** [comment]
@soloturn do you still have the issue ?

**Comment by soloturn** [comment]
it is not an issue. it is more a question if jgitver could and should be extended so it replaces ${project.version} in all pom files with the version generated, just as it replaces the version string. here the maven page about predefined properties: https://cwiki.apache.org/confluence/display/MAVEN/Maven+Properties+Guide.

**Comment by michael-wirth** [comment]
I'm facing the same issue when I use a parent pom.xml, which has been versioned with `jgitver`, in another project.

In my dependencyManagement I manage the version of my submodules in the same project. 

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>my-group</groupId>
                <artifactId>my-artifact</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

If I define this pom.xml as a parent in another project then Maven will resolve the wrong version number of the "my-artifact" dependency. It will use the `project.version` of the *new* (current) project instead of the parent version (where it was defined).

It would be helpful to have an option in `jgitver` to replace all ${project.version} variables in the current and all submodules.
