### ISSUE TITLE
Non-resolvable parent POM when using jgitver

### ISSUE THREAD

**Issue by HarrisKirk** [jgitver/jgitver-maven-plugin#40]
## Issue
[ERROR]     Non-resolvable parent POM when using jgitver

The parent version is clearly a specific "1.3.0" yet maven and jgitver are incorrectly trying to resolve the parent version as "3.1.1-pdot_224", which is the (correct) jgitver derived version for the artifact.

**version**:   0.3.0

**usage context**:

- [ ] mvn --version
Apache Maven 3.3.9 

- [ ] maven command line: mvn -P devopsProfileTest --file utd-lightbulb/ install

**Problem description**:
Here is the console error
```
[ERROR]   The project com.uptodate.microservice.lightbulb:utd-lightbulb:3.1.1-pdot_224 (C:\UNG\workspaces\NG\microservicetemplate\utd-lightbulb\pom.xml) has 1 error

[ERROR]     Non-resolvable parent POM for com.uptodate.microservice.lightbulb:utd-lightbulb:3.1.1-pdot_224: Failure to find com.uptodate.microservice.core:utd-core-parent:pom:3.1.1-pdot_224 in 

http://nexus01p:8081/nexus/content/repositories/releases was cached in the local repository, resolution will not be reattempted until the update interval of releases has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 10 -> [Help 2]
```

pom.xml is:
```
<parent>
		<groupId>com.uptodate.microservice.core</groupId>
		<artifactId>utd-core-parent</artifactId>
		<version>1.3.0</version>
</parent>
```
.mvn\jgitver.config.xml is:
```
<configuration>

</configuration>
```
ie, use all jgitver default values.

- *explain how to reproduce*
```
mvn -P devopsProfileTest --file utd-lightbulb/ install
```
Here are the tags
```
$ git tag --list
v1
v2
v3.1.1
```

The complete pom.xml is
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.uptodate.microservice.core</groupId>
		<artifactId>utd-core-parent</artifactId>
		<version>1.3.0</version>
	</parent>

	<groupId>com.uptodate.microservice.lightbulb</groupId>
	<artifactId>utd-lightbulb</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>UTD Lightbulb</name>
	<description>UTD Lightbulb</description>

	<modules>
		<module>utd-lightbulb-client</module>
		<module>utd-lightbulb-service</module>
		<module>utd-lightbulb-api</module>
	</modules>

	<properties>
		<java.version>1.8</java.version>
		<utd.starter.dependencies.version>2.4.0</utd.starter.dependencies.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.uptodate.microservice.core</groupId>
				<artifactId>utd-starter-dependencies</artifactId>
				<version>${utd.starter.dependencies.version}</version>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<scm>
		<developerConnection>scm:git:ssh://${scm.bb.user}@bitbucket.utd.com:7999/NG/microservicetemplate.git</developerConnection>
	  <tag>HEAD</tag>
  </scm>  	

</project>
```

**Comment by McFoggy** [comment]
@HarrisKirk can you try the following sample and tell me what is different from your use case please?

[issue-40.zip](https://github.com/jgitver/jgitver-maven-plugin/files/616933/issue-40.zip)

```
cd issue-40
git init
git config user.name nobody
git config user.email nobody@nowhere.com
git add .
git commit -m "initial commit"
cd parent-issue40
mvn install
cd ../multi
mvn validate
mvn install
mvn --file child1 install
```

**Comment by HarrisKirk** [comment]
```
cd issue-40
git init
git config user.name nobody
git config user.email nobody@nowhere.com
git add .
git commit -m "initial commit"
cd parent-issue40
# mvn install
cd ../multi
mvn validate
mvn install
mvn --file child1 install
```

I have commented the commend above that is different in your use case.   Your use case specifically builds the 'parent' artifact, but in my use case the parent is already built (ie, built WITHOUT jgitver) and available in our remote Nexus repo.

NOTE: You must clear the local maven cache of any "fr.brouillard.jgitver-issues:issue40-parent" artifacts to reproduce the problem.

In summary, then, to exactly reproduce the problem:
* Clear out any fr.brouillard.jgitver-issues:issue40-parent artifacts from the local maven repo ( xx/.m2/repository)
* download your issue40 zip into a clean directly
* run the commands you provided (being sure to comment-out  the line after "cd parent-issue40"

Thanks VERY much for looking into this.   

Harris

**Comment by McFoggy** [comment]
In the provided example, the parent project is built without jgitver, it could have been totaly external to the example. 
I will retry by setting as parent something already available in central as parent pom like `org.sonatype.oss:oss-parent:9`

**Comment by McFoggy** [comment]
sorry I do not reproduce using the following

[issue-40-sonatype-oss.zip](https://github.com/jgitver/jgitver-maven-plugin/files/617184/issue-40-sonatype-oss.zip)

and running 

```
rm -rf ~/.m2/repository/org/sonatype
cd multi
git init
git config user.name nobody
git config user.email nobody@nowhere.com
git add .
git commit -m "initial commit"
mvn validate
mvn install
mvn --file child1 install
```

Can you better describe your project/disk layout, especially:
- location of your multi project
- location of `.mvn`
- location of your maven local repository

**Comment by McFoggy** [comment]
From what I have already seen, I would say that your MLR is a sub-directory of the what maven will consider as the `multi-module root directory`.
It is what occures for example for the IT tests of jgitver-maven-plugin itself when run by maven-invoker. The  created mlr for the tests is created under `target/local-repo`.
For that specific purpose, one can use the `exclusions` tag inside the configuration (this is what the jgitver-maven-plugin uses).
But for your use case, no exclusions should be required, let's continue the investigations and please describe your paths.

**Comment by HarrisKirk** [comment]
Thank you for the rapid responses.   

Before we go too far into this, can we backup and return to the original zip you provided (issue-40.zip) and my 1-line commenting which exactly reproduces my problem.       Are you able to get the error doing the steps I described?   It's not clear to me that you were able to see the problem.

 I like your provided zip because it really does highlight my problem when I comment-out that 1 line.

H

**Comment by McFoggy** [comment]
@HarrisKirk for me the first example is the exact same than the second one except that `org.sonatype.oss:oss-parent:9` exist in central whereas `issue40-parent` does not exists anywhere.
Just removing the `mvn install` should not be enought to reproduce your problem, because maven must fail in not finding `issue40-parent:pom`.

I tested it and here is my result:

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for fr.brouillard.demos:jgitver-multi-parent:0.0.0-SNAPSHOT: Could not find artifact fr.brouillard.jgitver-issues:issue40-parent:pom:1 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 5, column 11 
```

which is totally normal.

How did you tested it? did you first deploy `issue40-parent:pom` to one of your repository? if yes then it is the same as using `org.sonatype.oss:oss-parent:9`. If not then you should face the same error than me. 

jgitver maven plugin does not influence dependency management but it influences the way pom are loaded in memory. And if by error it interferes with the loading of poms while it should not, then it will set the version to this POM object model to the one it calculated from git. It is the error you are seeing.
What I do not explain in your case is why the hell does jgitver intercept the loading of the parent pom whereas it should not... unless your local repository is a subdirectory of your multi module project or unless your locak repository is a child or sibling directory of `.mvn` one.

 Please explain me your directory layout.

**Comment by HarrisKirk** [comment]
Thanks very much.   I will be working on this later today or tomorrow and will reply.

**Comment by HarrisKirk** [comment]
![capture](https://cloud.githubusercontent.com/assets/2710359/20761389/d89e3f96-b6f0-11e6-83a3-a784d4c32012.PNG)

Attached is my file layout and additional observations.  
```mvn --file utd-lightbulb clean install``` ==> Non-resolvable parent POM

These 2 changes seemed to work
1) Do not invoke maven with "--file" option but cd into folder before calling maven 
2) moving the ".mvn" folder into "utd-lightbulb" (rather than .mvn sitting at the top)

**Comment by McFoggy** [comment]
@HarrisKirk I now reproduce the issue with the following project

[issue-40-reproduced.zip](https://github.com/jgitver/jgitver-maven-plugin/files/622443/issue-40-reproduced.zip)

and executing:

```
cd parent
mvn install
cd ../project
mvn --file multi validate
```

I'll investigate a bit more to fully understand where the problem comes from.
From the current understanding I have on maven core extensions, I am not sure that having the `.mvn` in an unrelated parent directory of your maven multi modules is _normal_.
I need to go a bit deeper in maven internals ; this part of maven, like some others, is quite obscure if not dark ;-)

So for sure for me the normal layout is to have the `.mvn` at the root of your multi module maven project and to work from there.

**Comment by HarrisKirk** [comment]
Yes, I can ensure that the ```.mvn``` is placed at the root - so this aspect is not a problem.

It would be helpful to have jgitver recognize the ```--file``` command line option.

Thanks very much for your help.    You can consider this resolved whenever you want.

**Comment by McFoggy** [comment]
I am glad that we could find a workaround for the moment.

But still I'll investigate the topic to be sure where the problem comes from.
Many thanks for your time for reporting and enjoy jgitver ;-)

**Comment by McFoggy** [comment]
@HarrisKirk I have looked a bit more into the details of this. For me the problem is maven related, and unless we find better maven API to use, I cannot find a way to correct this behavior in jgitver only.

The problem comes from the usage of `mavenSession.getRequest().getMultiModuleProjectDirectory()` method in jgitver-maven-plugin [JGitverModelProcessor#calculateVersionIfNecessary](https://github.com/jgitver/jgitver-maven-plugin/blob/0.4.0/src/main/java/fr/brouillard/oss/jgitver/JGitverModelProcessor.java#L97). 

This method, which was the only one I found to retrieve the root pom of a multi module maven project, seems to work only when maven is invoked from inside one the project of the multi-module.

Sorry but for the moment, you have to execute maven from your multi-module and do not use `--file` or something from outside of it.

**Comment by HarrisKirk** [comment]
@McFoggy Thank you very much for looking into this.     We have the workaround (ie, to "cd" into the directory prior to running maven) and will continue the evaluation of jgitver.

**Comment by McFoggy** [comment]
you're welcome, do not hesitate to open new issues/questions when needed.
you can also keep me privately (by mail) informed on your usage if you want to.
