### ISSUE TITLE
Somehow messes with unrelated dependencies

### ISSUE THREAD

**Issue by rfvermut** [jgitver/jgitver-maven-plugin#60]
## Issue

**version**: 1.0.0

**usage context**: maven command line: 3.3.9

**Problem description**:

How to reproduce:
- follow the steps in [README/Example](https://github.com/jgitver/jgitver-maven-plugin/blob/master/README.md#example)

```
# cd /tmp
# mvn archetype:generate -B -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart \\n
  -DarchetypeVersion=1.1 -DgroupId=com.company -DartifactId=jgitver-tester -Dversion=0 -Dpackage=com.company.project
....
# mvn validate
[INFO] jgitver-maven-plugin is about to change project(s) version(s)
[INFO]     com.company::jgitver-tester::0 -> 1.0.1-SNAPSHOT
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building jgitver-tester 1.0.1-SNAPSHOT
```
No surprises.

After that I run a generic plugin command with empty local repo so it will start resolving from scratch
```
# mvn -N org.codehaus.mojo:versions-maven-plugin:2.4:update-child-modules -Dmaven.repo.local=tmprepo
...
[ERROR] Plugin org.codehaus.mojo:versions-maven-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:versions-maven-plugin:jar:2.4: Could not find artifact org.codehaus.mojo:mojo-parent:pom:1.0.1-SNAPSHOT -> [Help 1]
```
Notice the *1.0.1-SNAPSHOT*.

Works with plugin disabled:
```
# mvn -N org.codehaus.mojo:versions-maven-plugin:2.4:update-child-modules -Dmaven.repo.local=tmprepo -Djgitver.skip=true
...
[INFO] All child modules are up to date.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by McFoggy** [comment]
can you try by changing your maven local repo location. From what I read from your description you put in the same directory than the current project. 
Please retry with something like: `-Dmaven.repo.local=/tmp/tmprepo`.

If that solves the problem, then read below for explanations.
To bypass this behavior, 2 solutions:
- declare some directory exclusion using [jgitver-maven-plugin configuration file](https://github.com/jgitver/jgitver-maven-plugin/blob/master/README.md#configuration)
- do not store POMs unrelated to your project in a sub directory of the root one (the one declaring the jgitver extension). 

If you look [jgitver-maven-plugin config file](https://github.com/jgitver/jgitver-maven-plugin/blob/master/.mvn/jgitver.config.xml), you will see that some exclusions are declared there also. It is because during tests (mainly integration tests) we use sub directories and local repositories for which we do not want jgitver to modify versions ; exactly like the case you describe.
If you had put your local repo everywhere else on your disk it should have worked... bad luck ;-)

Why does this occur? Because when jgitver is activated, when a POM is loaded by maven, jgitver intercept this loading action and if the POM is located under the root project (the one that activated jgitver) then the POM version is replaced with the calculated version of jgitver. Hope it clarifies the behavior you have seen.

**Comment by rfvermut** [comment]
yes, sounds very logical now when you explained it... let me try.

**Comment by rfvermut** [comment]
Still worked strange with relative outside path `../tmprepo `.
Worked fine when added `tmprepo` to exclusions.

**Comment by McFoggy** [comment]
> Still worked strange with relative outside path ../tmprepo

I'll give it a try to analyze deeper.
Thanks for reporting.
