### ISSUE TITLE
Enable profile if release (of if dirty)

### ISSUE THREAD

**Issue by vromero** [jgitver/jgitver-maven-plugin#62]
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/jgitver/jgitver-maven-plugin/wiki) 

## Issue

**version**: 1.0.0

**usage context**:

- [x] maven command line: 3.5.0

**Problem description**:

I keep finding myself needing to do special things when on a release that doesn't happen on a dirty build or the other way around. The good-old release plugin that this extension deprecates had the [releaseProfiles](http://maven.apache.org/maven-release/maven-release-plugin/perform-mojo.html#releaseProfiles) that could be activated only on releases. I believe jgitver should support either of the following:
- support a `releaseProfiles=commaSeparatedProfiles` and/or `dirtyProfiles=commaSeparatedProfiles`
- set the `jgitver.dirty` a systemProperty, so profiles could be activated by `jgitver.dirty` or `!jgitver.dirty` (I assume this should [work](https://github.com/apache/maven/blob/master/maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/PropertyProfileActivator.java#L78) already but for some reason it doesn't).

**Comment by McFoggy** [comment]
The profile activation does not work because the `ProfileActivationContext` object _(holding properties and used during the property [evaluation](https://github.com/apache/maven/blob/master/maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/PropertyProfileActivator.java#L45))_ is built before the jgitver extension is called, so none of the properties maps (user & system) contain jgitver properties.

jgitver is fired too late in the build process to be picked up by the any of the `ProfileActivator`.

Regarding your demand of a `releaseProfiles=commaSeparatedProfiles` property. This is not possible to me, jgitver has no knowledge of a `release`.  
On the opposite, I think `dirtyProfiles=commaSeparatedProfiles` could be a more valid demand. Would you think it would still be needed if the jgitver calculated properties were made available to the profile activation?

**Comment by vromero** [comment]
Thanks for taking the time to reploy this

> The profile activation does not work because the ProfileActivationContext object (holding properties and used during the property evaluation) is built before the jgitver extension is called, so none of the properties maps (user & system) contain jgitver properties.
> 
> jgitver is fired too late in the build process to be picked up by the any of the ProfileActivator.

I see

> Regarding your demand of a releaseProfiles=commaSeparatedProfiles property. This is not possible to me, jgitver has no knowledge of a release.
> On the opposite, I think dirtyProfiles=commaSeparatedProfiles could be a more valid demand. 

I understand that with jgitver there is no _release_ per-se. What I actually meant is a concept opposed to `dirtyProfiles`. Something like `nonDirtyProfiles`. Just to give an example, lets say that someone needs to send a docker image to a repo x on dirty builds and to repy y on non dirty builds. That someone could have `dirtyProfiles=dockerSnapshot` and `nonDirtyProfiles=dockerRelease`.

It can be argued thow that given that when `-P` is passed, only the passed profiles are active, `nonDirtyProfiles` would not be necessary (or the other way around).

> Would you think it would still be needed if the jgitver calculated properties were made available to the profile activation?

IMHO this would be the ideal solution, brings the freedom to the user to do whatever they want in the best place possible because here maven even support the negation with `!`.

**Comment by McFoggy** [comment]
@vromero please look at following it tests [issue-62.1](https://github.com/jgitver/jgitver-maven-plugin/tree/master/src/it/issues/issue-62.1) & [issue-62.2](https://github.com/jgitver/jgitver-maven-plugin/tree/master/src/it/issues/issue-62.2).

I think latest version will answer your needs. If not let's continue discussions.

**Comment by vromero** [comment]
That is great! thank you!
I'll give it a try and feedback ASAP.

**Comment by vromero** [comment]
Works like a charm, thanks!

**Comment by McFoggy** [comment]
Glad to hear that!
