### ISSUE TITLE
Gitbucket Jenkins trigger

### ISSUE THREAD

**Issue by kingdevnl** [jgitver/jgitver-maven-plugin#77]
Any clues when the Gitbucket Jenkins trigger it's gonna be fixed?
Are there any workarounds for this available yet?

**Comment by McFoggy** [comment]
can you explain a bit more what you are talking about please?

**Comment by kingdevnl** [comment]
So i trtied to setup https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket, But Jenkins is ignoring the Pushes

**Comment by McFoggy** [comment]
Ok but the problem is totally unrelated to [jgitver-maven-plugin](https://github.com/jgitver/jgitver-maven-plugin), it is purelly related to gitbucket & jenkins.

Nevertheless I have provided to [gitbucket](https://github.com/gitbucket/gitbucket) a fix for gitbucket/gitbucket#1844, it has been integrated inside `4.21.0` version, please use latest version [4.21.2](https://github.com/gitbucket/gitbucket/releases/tag/4.21.2) that additionaly correct bugs of initial `4.21.0` release.

**Comment by kingdevnl** [comment]
Ok, something different, tho
Im actually on 4.21.2,
