### ISSUE TITLE
document exclusion of repositories below root directory

### ISSUE THREAD

**Issue by McFoggy** [jgitver/jgitver-maven-plugin#83]
In order to help users, the wiki/README should expose a common failure section in which is described the problem of hosting a repository under the root directroy controlled by jgitver.

This occures when:
- your developping  maven plugin with invoker integration tests
- you host a repository or the local repository in some sub directories

**Comment by fjakop** [comment]
The same issue occurs on GitlabCI with default maven runner configuration, which sets -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository by default, where $CI_PROJECT_DIR is the checkout/root dir.

Since the local repo is set by maven variable wouldn't it be possible to let jGitVer act correctly in this scenarios?

**Comment by McFoggy** [comment]
the README already document this

https://github.com/jgitver/jgitver-maven-plugin#build-fail-because-all-project-plugins--dependencies-resolve-to-the-same-version

**Comment by McFoggy** [comment]
> Since the local repo is set by maven variable wouldn't it be possible to let jGitVer act correctly in this scenarios?

@fjakop you mean that jgitver should detect that the MLR is a subdirectory and thus should exclude it automatically ?

**Comment by fjakop** [comment]
Yes, exactly that. I think the MLR variable is known to jGitVer.

07.01.2021 16:36:13 Matthieu Brouillard <notifications@github.com>:

**Comment by McFoggy** [comment]
can you please create an issue for this enhancement request ?
